/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/my-orders` | `/my-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/product-detail` | `/product-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/my-cart` | `/my-cart`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/my-orders` | `/my-orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/product-detail` | `/product-detail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/my-cart` | `/my-cart`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/my-orders${`?${string}` | `#${string}` | ''}` | `/my-orders${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/product-detail${`?${string}` | `#${string}` | ''}` | `/product-detail${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/my-cart${`?${string}` | `#${string}` | ''}` | `/my-cart${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/my-orders` | `/my-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/product-detail` | `/product-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/my-cart` | `/my-cart`; params?: Router.UnknownInputParams; };
    }
  }
}
