/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/add-product` | `/add-product`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/add-remove-slots/AddSlotForm` | `/add-remove-slots/AddSlotForm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/add-remove-slots` | `/add-remove-slots`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/delivery` | `/delivery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/edit-product` | `/edit-product`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/manage-slots` | `/manage-slots`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/packaging` | `/packaging`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/todays-orders` | `/todays-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/complaints` | `/complaints`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/product-detail/[id]` | `/product-detail/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/add-product` | `/add-product`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/add-remove-slots/AddSlotForm` | `/add-remove-slots/AddSlotForm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/add-remove-slots` | `/add-remove-slots`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/delivery` | `/delivery`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/edit-product` | `/edit-product`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/manage-slots` | `/manage-slots`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/packaging` | `/packaging`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/todays-orders` | `/todays-orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/complaints` | `/complaints`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/product-detail/[id]` | `/product-detail/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/add-product${`?${string}` | `#${string}` | ''}` | `/add-product${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/add-remove-slots/AddSlotForm${`?${string}` | `#${string}` | ''}` | `/add-remove-slots/AddSlotForm${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/add-remove-slots${`?${string}` | `#${string}` | ''}` | `/add-remove-slots${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/delivery${`?${string}` | `#${string}` | ''}` | `/delivery${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/edit-product${`?${string}` | `#${string}` | ''}` | `/edit-product${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/manage-slots${`?${string}` | `#${string}` | ''}` | `/manage-slots${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/packaging${`?${string}` | `#${string}` | ''}` | `/packaging${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/todays-orders${`?${string}` | `#${string}` | ''}` | `/todays-orders${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/complaints${`?${string}` | `#${string}` | ''}` | `/complaints${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/add-product` | `/add-product`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/add-remove-slots/AddSlotForm` | `/add-remove-slots/AddSlotForm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/add-remove-slots` | `/add-remove-slots`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/delivery` | `/delivery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/edit-product` | `/edit-product`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/manage-slots` | `/manage-slots`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/packaging` | `/packaging`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/todays-orders` | `/todays-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/complaints` | `/complaints`; params?: Router.UnknownInputParams; } | `${'/(drawer)'}/product-detail/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/product-detail/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(drawer)'}/product-detail/[id]` | `/product-detail/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
